additionalRepositories:
  - url: https://github.com/yogesh-ti/simple-api
    checkoutLocation: simple-api

tasks:
  - name: gui
    init: |
      yarn install
    command: |
      export FULLSTACK_BACKEND='gp url 8000'
      yarn start

  - name: api
    before: |
      cd ../simple-api
    init: |
      pip install fastapi uvicorn[standard]
    command: |
      export FULLSTACK_FRONTEND='gp url 3000'
      uvicorn main:app --reload

workspaceLocation: simple-gui/fullstack.code-workspace

