tasks:
  - name: gui
    init: |
      yarn install
    command: |
      export FULLSTACK_BACKEND='gp url 8000'
      yarn start

  - name: api
    before: |
      cd ..
      git clone -b passwordless-auth --single-branch git@github.com:yogesh-ti/simple-api.git
      cd simple-api
      rm -rf .git
    init: |
      pip install fastapi uvicorn[standard]
    command: |
      export FULLSTACK_FRONTEND='gp url 3000'
      uvicorn main:app --reload

