tasks:
  - name: gui
    init: |
      yarn install
    command: |
      REACT_APP_FULLSTACK_BACKEND=`gp url 8000` \
      yarn start

  - name: api
    before: |
      cd ..
      git clone -b develop --single-branch https://github.com/yogesh-ti/simple-api.git
      cd simple-api
      rm -rf .git
    init: |
      pip install fastapi uvicorn[standard]
    command: |
      export FULLSTACK_FRONTEND=`gp url 3000`
      uvicorn main:app --reload

